### PR TITLE
Add wmi kernel module for some Clevo notebooks used by Tuxedo

### PR DESCRIPTION
**Pull request by karolherbst**
They should work fine for Tuxedos one. I have a XMG based one for which the module works excellent.

This module adds keyboard LED control and Airplane mode Fn-keys. Also it enables the user to configure the color of the keyboard LED areas through module parameters.

I've added a tuxedo_wmi.conf file, because the module lacks english documentation a bit. I hope the config file clears everything up.

### CODE REVIEW

**Comment by hwoarang** [comment]
Hmm I had a second look and this does not appear a valid and maintained package but rather something someone hacked together and uploaded on a forum. Since it's a kernel module, it's likely to break on kernel updates as well without a dedicated maintainer. If this becomes a real package we can have it in the tree. But until then it needs to be maintained outside the tree. So I have reverted the commit

**Comment by karolherbst** [comment]
yeah, no problems. I am just using this module and thought that somenody with a compatible laptop might want to have a proper ebuild or something.

I am using this for a year or something and it never broke so far.

**Comment by mrueg** [comment]
@hwoarang will you import the merged PRs to the main tree?

**Comment by karolherbst** [comment]
I don't know how official this module is, but there just was an update yesterday or today.

**Pull request merged**
